vars:
  file: some_data

files:
  - path: template_remote.txt
    get:
      # get a file (raw) from 'GitHub'
      url: https://raw.githubusercontent.com/kozmod/progen-examples/main/flags/pf/assets/template.txt
  - path: template_data.txt
    data: |
      some_data_2
  - path: template_local.txt
    local: ../assets/local.txt


