dirs0:
  - api/v0
dirs:
  - api/v1
cmd:
  - exec: chmod
    args: [ -R, 777, api/v0 ]
dirs1:
  - api/v2
cmd1:
  - exec: chmod
    args: [ -R, 777, api/v2 ]
dirs2:
  - api/v3
cmd2:
  - exec: chmod
    args: [ -R, 777, api/v2 ]
