.PHONT: run.without
run.without: ## Run 'progen' without `-errstack` arg
	@progen -v -awd=out -f ../progen.yml

.PHONT: run.sparse
run.with:  ## Run 'progen' with `-errstack` arg
	@progen -v -errstack -awd=out -f ../progen.yml
